#!/bin/bash

ADMIN_USER="carbonio-message-broker-admin"
CONSUL_TOKEN_PATH="/etc/carbonio/message-broker/service-discover/token"
RABBITMQ_COMMANDS_FOLDER="/opt/zextras/common/bin"

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

get_consul_kv() {
  KEY=$1
  CONSUL_VALUE=$(consul kv get -token-file="$CONSUL_TOKEN_PATH" "$KEY" || echo "")
  EXIT_CODE=$?
  if [[ "$EXIT_CODE" != "0" ]]; then
    CONSUL_VALUE=""
  fi
}

TMP_PATH=$PATH
export PATH="$PATH:$RABBITMQ_COMMANDS_FOLDER"
get_consul_kv "$ADMIN_USER/username"; USERNAME=$CONSUL_VALUE
get_consul_kv "$ADMIN_USER/password"; PASSWORD=$CONSUL_VALUE
RESULT=999
if [[ "$USERNAME" != "" && "$PASSWORD" != "" ]]; then
  rabbitmqctl authenticate_user "$USERNAME" "$PASSWORD"
  RESULT=$?
fi

if [[ "$RESULT" != "0" ]]; then
  consul kv put -token-file="$CONSUL_TOKEN_PATH" "$ADMIN_USER/username" "$ADMIN_USER"
  PASSWORD=$(openssl rand -hex 16 | tr -d '\n')
  consul kv put -token-file="$CONSUL_TOKEN_PATH" "$ADMIN_USER/password" "$PASSWORD"
  rabbitmqctl add_user $ADMIN_USER "$PASSWORD"
  rabbitmqctl set_permissions -p "/" "$ADMIN_USER" ".*" ".*" ".*"
  rabbitmqctl set_user_tags "$ADMIN_USER" administrator
fi
export PATH=$TMP_PATH

echo "Carbonio Message Broker administration user added."