#!/bin/bash

# SPDX-FileCopyrightText: 2023 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

MAIN_SERVICE_NAME="carbonio-message-broker"
CONSUL_TOKEN_PATH="/etc/carbonio/message-broker/service-discover/token"
RABBITMQ_COMMANDS_FOLDER="/opt/zextras/common/bin"
RABBITMQ_NODE_NAME="carbonio-message-broker-clustered"

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

get_consul_kv() {
  KEY=$1
  CONSUL_VALUE=$(consul kv get -token-file="$CONSUL_TOKEN_PATH" "$KEY")
}

TMP_PATH=$PATH
export PATH="$PATH:$RABBITMQ_COMMANDS_FOLDER"
get_consul_kv "$MAIN_SERVICE_NAME/default/username" >/dev/null 2>&1; USERNAME=$CONSUL_VALUE
get_consul_kv "$MAIN_SERVICE_NAME/default/password" >/dev/null 2>&1; PASSWORD=$CONSUL_VALUE

RESULT=999
if [[ "$USERNAME" != "" && "$PASSWORD" != "" ]]; then
  rabbitmqctl authenticate_user --node "$RABBITMQ_NODE_NAME" "$USERNAME" "$PASSWORD" >/dev/null 2>&1
  RESULT=$?
fi

if [[ "$RESULT" != "0" ]]; then
  if [[ "$USERNAME" != "$MAIN_SERVICE_NAME" ]]; then
    consul kv put -token-file="$CONSUL_TOKEN_PATH" "$MAIN_SERVICE_NAME/default/username" "$MAIN_SERVICE_NAME"
  fi
  PASSWORD=$(openssl rand -hex 16 | tr -d '\n')
  consul kv put -token-file="$CONSUL_TOKEN_PATH" "$MAIN_SERVICE_NAME/default/password" "$PASSWORD"
  rabbitmqctl add_user --node "$RABBITMQ_NODE_NAME" $MAIN_SERVICE_NAME "$PASSWORD" >/dev/null 2>&1
  EXIT_CODE=$?
  if [[ "$EXIT_CODE" != "0" ]]; then
    rabbitmqctl change_password --node "$RABBITMQ_NODE_NAME" $MAIN_SERVICE_NAME "$PASSWORD" >/dev/null 2>&1
    echo "Changed password for the user $MAIN_SERVICE_NAME"
  else
    rabbitmqctl set_permissions --node "$RABBITMQ_NODE_NAME" -p "/" "$MAIN_SERVICE_NAME" ".*" ".*" ".*" >/dev/null 2>&1
    echo "User $MAIN_SERVICE_NAME added"
  fi
else
  echo "User $MAIN_SERVICE_NAME already exists"
fi
export PATH=$TMP_PATH
